spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kipao
    dialect: InnoDB
    username: root
    password: Oracle!19
    maxActive: '15'
    maxIdle: '5'
    minIdle: '2'
    initialSize: '5'
    removeAbandoned: 'true'
    resources: 
        cache:
            cachecontrol:
                max-age: 120
                must-revalidate: true

  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc:
    swagger-ui:
      path: /routes
        
server:
   port: 8090
security:
   firebase-props:
      database-url: https://bsi-kipao-default-rtdb.firebaseio.com/
      enable-check-session-revoked: false
      enable-logout-everywhere: false
      session-expiry-in-days: 5
   cookie-props:
      max-age-in-minutes: 7200
      http-only: true
      secure: true
      domain: ${CORS_DOMAIN}
      path: /
   allowed-origins:
   - https://${CORS_DOMAIN}
   - http://localhost:4000
   allowed-methods:
   - GET
   - POST
   - PUT
   - PATCH
   - DELETE
   - OPTIONS
   allowed-headers:
   - Authorization
   - Origin
   - Content-Type
   - Accept
   - Accept-Encoding
   - Accept-Language
   - Access-Control-Allow-Origin
   - Access-Control-Allow-Headers
   - Access-Control-Request-Method
   - X-Requested-With
   - X-Auth-Token
   - X-Xsrf-Token
   - Cache-Control
   - Id-Token
   allowed-public-apis:
   - /favicon.ico
   - /session/login
   - /public/**
   - /test/**
   exposed-headers:
   - X-Xsrf-Token
   valid-application-roles:
   - ROLE_SUPER
   - ROLE_ADMIN
   - ROLE_EMPLOYEE
   - ROLE_CUSTOMER
   super-admins: ${SUPER_ADMINS}
   test:
     login:
       enabled: ${TEST_LOGIN_ENABLED}
logging:
   level:
      root: WARN
      org:
        springframework:
          web: DEBUG
        hibernate: WARN
      io:
        thepro: DEBUG
   pattern:
     console: "%d{HH:mm:ss} || %highlight(%5p) < %highlight(%-35.35logger{35}) > %highlight(%m%n)"
    